"""add_readable_id_to_order

Revision ID: 017cbf7dc339
Revises: a04cedc3b107
Create Date: 2025-12-07 23:00:06.176946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017cbf7dc339'
down_revision: Union[str, Sequence[str], None] = 'a04cedc3b107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('readable_id', sa.Integer(), sa.Identity(always=False, start=1000), nullable=False))
    op.create_unique_constraint(None, 'order', ['readable_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_column('order', 'readable_id')
    # ### end Alembic commands ###
