"""remove_slug_from_category_and_blogpost

Revision ID: 1126fed8fb7e
Revises: d3bcfbf0e4a4
Create Date: 2025-12-06 20:49:47.336665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1126fed8fb7e'
down_revision: Union[str, Sequence[str], None] = 'd3bcfbf0e4a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogpost_slug'), table_name='blogpost')
    op.drop_column('blogpost', 'slug')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    op.add_column('blogpost', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_blogpost_slug'), 'blogpost', ['slug'], unique=True)
    # ### end Alembic commands ###
