"""add_soft_delete_to_user

Revision ID: 9c538c478f6a
Revises: 1126fed8fb7e
Create Date: 2025-12-06 22:47:21.109916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c538c478f6a'
down_revision: Union[str, Sequence[str], None] = '1126fed8fb7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'deleted')
    # ### end Alembic commands ###
