"""add_soft_delete_to_product

Revision ID: a04cedc3b107
Revises: 9c538c478f6a
Create Date: 2025-12-06 23:13:58.090413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04cedc3b107'
down_revision: Union[str, Sequence[str], None] = '9c538c478f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('product', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'deleted_at')
    op.drop_column('product', 'deleted')
    # ### end Alembic commands ###
