"""add_otp_fields_to_user

Revision ID: c47a2ade5b95
Revises: c85b956cfbf0
Create Date: 2025-12-06 16:22:42.716623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c47a2ade5b95'
down_revision: Union[str, Sequence[str], None] = 'c85b956cfbf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_expires_at')
    op.drop_column('user', 'otp_code')
    # ### end Alembic commands ###
